---
title: "STAT601 LAB5"
author: "Chengen Xie (cx22)"
date: "February 19, 2015"
output: pdf_document
---
#1

$$
p(N,\beta|y) \propto p(y|N,\beta)p(N)p(\beta)
= \frac{25^N\beta^y(1-\beta)^{N-y}e^{-25}{y!(N-y!)}
$$

#2
$$
P(N|y,\beta) = \frac{P(N,y,\beta)}{p(y,\beta)}
\propto \frac{p(y|N,\beta)p(N)p(\beta)}{p(y|\beta)}
\propto p(y|N,\beta)p(N)
= (^{N}_{y})p^y(1-\beta)^{N-y}\frac{25^N}{N!}e^{-25}
\propto \frac{(25(1-\beta))^{N-y}}{(N-y)!}
$$

Therefore, N-y ~ Poisson($25(1-\beta)$)


$$
p(\beta|y,N) 
\propto p(y|N,\beta)p(\beta)
\propto (1-\beta)^{N-y}\beta^{y}
$$


Therefore, $\beta$~Beta(y+1,N-y+1)


#3
```{r}
Sample <- 10000

N<-rep(0,Sample)
Beta<-rep(0,Sample)
N[1] <- 50
Beta[1] <- 0.05

for (i in 2:Sample){
  N[i] <- rpois(1,25*(1-Beta[i-1])) + 20
  Beta[i] <- rbeta(1,21,N[i]-20+1)
}
```

#4
```{r}
xseq <- seq(1,10)
plot(xseq,Beta[1:10])
lines(xseq,Beta[1:10])
plot(xseq,N[1:10])
lines(xseq,N[1:10])
```

#5
```{r}
#central 90% posterior credible interval for beta
quantile(Beta[-c(1:1000)],c(0.05,0.95))
```

#6
```{r}
#probability that exactly 20 people were polled
sum(N[-c(1:1000)]==20)/(Sample-1000)
```
